# Generated by Django 5.0 on 2023-12-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBankApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['apellido'], 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'ordering': ['numero'], 'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['numero'], 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AddField(
            model_name='cuenta',
            name='saldo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
