# Generated by Django 5.0 on 2023-12-25 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBankApp', '0002_alter_cliente_options_alter_cuenta_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
    ]
