# Generated by Django 5.0 on 2023-12-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBankApp', '0009_alter_cliente_dni_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='titular',
            field=models.CharField(max_length=40),
        ),
    ]
