# Generated by Django 5.0 on 2023-12-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBankApp', '0010_alter_cuenta_titular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
