# Generated by Django 5.0 on 2023-12-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBankApp', '0011_alter_cuenta_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('puesto', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Nomina',
                'ordering': ['apellido'],
            },
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
