# Generated by Django 5.0 on 2023-12-26 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBankApp', '0012_nomina_delete_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
    ]
